version: "3.7"

services:
  elastic:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
        - elastic
